export const data = {
    ['/clients']: [
        {
            "id": 1,
            "name": "Иван",
            "lastname": "Иванов",
            "midname": "Иванович",
            "reg": "В004КО142",
            "brand": "Toyota",
            "model": "Mark 2",
            "year": "1995",
            "vin": "ST202",
            "color": "Синий",
            "descriptionCar": "Еще какие-нибудь данные",
            "card": "Развернутый комментарий с датой"
        },
        {
            "id": 2,
            "name": "Петр",
            "lastname": "Перов",
            "midname": "Петрович",
            "reg": "С543КЕ142",
            "brand": "BEMEWE",
            "model": "X5",
            "year": "1995",
            "vin": "ST202",
            "color": "Синий",
            "descriptionCar": "Еще какие-нибудь данные",
            "card": "Развернутый комментарий с датой"
        },
        {
            "id": 3,
            "name": "Михаил",
            "lastname": "Михайлов",
            "midname": "Михайлович",
            "reg": "С765КЕ142",
            "brand": "Toyota",
            "model": "Harrier",
            "year": "1995",
            "vin": "ST202",
            "color": "Синий",
            "descriptionCar": "Еще какие-нибудь данные",
            "card": "Развернутый комментарий с датой"
        },
        {
            "id": 4,
            "name": "Денис",
            "lastname": "Денчик",
            "midname": "Денчикович",
            "reg": "К666КЕ142",
            "brand": "Mitsubishi",
            "model": "Galant",
            "year": "1995",
            "vin": "ST202",
            "color": "Синий",
            "descriptionCar": "Еще какие-нибудь данные",
            "card": "Развернутый комментарий с датой"
        },
        {
            "id": 5,
            "name": "Даня",
            "lastname": "Данечкин",
            "midname": "Данечкович",
            "reg": "С976ММ142",
            "brand": "Toyota",
            "model": "Carina ED",
            "year": "1995",
            "vin": "ST202",
            "color": "Синий",
            "descriptionCar": "Еще какие-нибудь данные",
            "card": "Развернутый комментарий с датой"
        },
    ],
    ['/clients/1']: {
        "id": 1,
        "name": "Иван",
        "lastname": "Иванов",
        "midname": "Иванович",
        "reg": "О004КО142",
        "brand": "Toyota",
        "model": "Mark 2",
        "year": "1995",
        "vin": "ST202",
        "color": "Синий",
        "descriptionCar": "Еще какие-нибудь данные",
        "card": "Развернутый комментарий с датой"
    },
    ['/clients/2']: {
        "id": 2,
        "name": "Петр",
        "lastname": "Перов",
        "midname": "Петрович",
        "reg": "С543КЕ142",
        "brand": "BEMEWE",
        "model": "X5",
        "year": "1995",
        "vin": "ST202",
        "color": "Синий",
        "descriptionCar": "Еще какие-нибудь данные",
        "card": "Развернутый комментарий с датой"
    },
    ['/clients/3']: {
        "id": 3,
        "name": "Михаил",
        "lastname": "Михайлов",
        "midname": "Михайлович",
        "reg": "С765КЕ142",
        "brand": "Toyota",
        "model": "Harrier",
        "year": "1995",
        "vin": "ST202",
        "color": "Синий",
        "descriptionCar": "Еще какие-нибудь данные",
        "card": "Развернутый комментарий с датой"
    },
    ['/clients/4']: {
        "id": 4,
        "name": "Денис",
        "lastname": "Денчик",
        "midname": "Денчикович",
        "reg": "К666КЕ142",
        "brand": "Mitsubishi",
        "model": "Galant",
        "year": "1995",
        "vin": "ST202",
        "color": "Синий",
        "descriptionCar": "Еще какие-нибудь данные",
        "card": "Развернутый комментарий с датой"
    },
    ['/clients/5']: {
        "id": 5,
        "name": "Даня",
        "lastname": "Данечкин",
        "midname": "Данечкович",
        "reg": "С976ММ142",
        "brand": "Toyota",
        "model": "Carina ED",
        "year": "1995",
        "vin": "ST202",
        "color": "Синий",
        "descriptionCar": "Еще какие-нибудь данные",
        "card": "Развернутый комментарий с датой"
    },
}